name: Build App1

on:
  push:
    branches: [main]
    paths:
      - 'app1/**'
      - 'common/**'
      - '.github/workflows/app1.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/gradle-build@v1
        with:
          name: app1
