name: Build App2

on:
  push:
    branches: [main]
    paths:
      - 'app2/**'
      - 'common/**'
      - '.github/workflows/app2.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/gradle-build
        with:
          name: app1
